### ISSUE TITLE
Decimal number of replicas

### ISSUE THREAD

**Issue by robert-sanfeliu** [eu-nebulous/optimiser-controller#119]
Given the following APP definition:

![Image](https://github.com/user-attachments/assets/8099f26a-9be9-40bb-a97e-b842b92c206f)

![Image](https://github.com/user-attachments/assets/9a604542-c20d-493c-8514-c568a8f5e58b)

Solver returns decimal values for the optimisation variable "replicas":

![Image](https://github.com/user-attachments/assets/333a57e5-d9af-4d41-bd83-fffe0b7decc9)

Optimiser controller then generates a vela file with decimal values:

```
..,.
      value: "3zk6_dJTCBK6MkcwnLnB"
      labels:
        app: "firecoat-persist"
      resources: {}
    traits:
    - type: "scaler"
      properties:
        replicas: 3.000000000000001
    - type: "affinity"
      properties:
        nodeAffinity:
          required:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "nebulouscloud.eu/firecoat-persist"
                operator: "In"
                values:
                - "yes"

EOF
sudo chown ubuntu:ubuntu /home/ubuntu/fireCOAT_2025-06-12_001.yaml
sudo -H -u ubuntu bash -c 'vela up -f  /home/ubuntu/fireCOAT_2025-06-12_001.yaml'
```

And Kubevela complains with:

```
[3939t0@ip-172-31-32-104.eu-central-1.compute.internal;deploy_app_3db2f-20;07:44:00] Applying an application in vela K8s object format...
[3939t0@ip-172-31-32-104.eu-central-1.compute.internal;deploy_app_3db2f-20;07:44:00] error: cannot update object: admission webhook "validating.core.oam.dev.v1beta1.applications" denied the request: field "schematic": Invalid value error encountered, cannot evaluate trait "scaler": invalid template of trait scaler after merge with parameter and context: parameter.replicas: 2 errors in empty disjunction: (and 8 more errors).
[3939t0@ip-172-31-32-104.eu-central-1.compute.internal;deploy_app_3db2f-20;07:44:00] Failed to execute task: Script failed with exit code 1
```
